### ISSUE TITLE
How to run the code for the sample data given in the datasets folder?

### ISSUE THREAD

**Issue by chanchalIITP** [JetBrains-Research/authorship-detection#2]
Hello,
The paper seems very interesting to me.
Can you please give a step-by-step guide for running the given model for the sample dataset (eg. cpp samples)?

**Comment by egor-bogomolov** [comment]
Hello @chanchalIITP and thanks for your patience! I will add a proper guide and switch to the updated version of [astminer](https://github.com/JetBrains-Research/astminer) in the next couple of days!

**Comment by chanchalIITP** [comment]
Thanks a lot, Sir.

**Comment by egor-bogomolov** [comment]
Sorry for the long wait! I've added instructions to run cross-validation on arbitrary data in README. For example, you can download [java40](https://github.com/xinyu1118/authorship_attribution) data and run experiments on it.

**Comment by chanchalIITP** [comment]
Thanks a lot.
I will try to execute now.
